'use client';

import {
  Auth0Provider,
  Auth0ProviderOptions,
  AppState,
  User,
} from "@auth0/auth0-react";

import { useRouter } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Providers({ children }: { children: React.ReactNode }) {
  const router = useRouter();

  const onRedirectCallback: (appState?: AppState, user?: User) => void = (
    appState
  ) => {
    router.replace(appState?.returnTo || "/");
  };

  if (!process.env.NEXT_PUBLIC_DOMAIN || !process.env.NEXT_PUBLIC_CLIENT_ID) throw new Error("Missing environment variables");

  const providerConfig: Auth0ProviderOptions = {
    domain: process.env.NEXT_PUBLIC_DOMAIN,
    clientId: process.env.NEXT_PUBLIC_CLIENT_ID,
    onRedirectCallback,
    authorizationParams: {
      redirect_uri: typeof window !== "undefined" ? window.location.origin : undefined,
      audience: process.env.NEXT_PUBLIC_AUDIENCE
    },
  };

  return <Auth0Provider {...providerConfig}>{children}</Auth0Provider>;
}

